#根据uid查询rids
GET http://localhost:8003/api/user/rids/3
Accept: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJZQXRFZ0VpNnBQdy9YalV2NU1xTTlSNnhKM3g0VGpXeG5BMTNRS0ZiUDVGN1M5OWlOTkV0dnVwS1lUcCtGN2VkZXZmZVk0ZXRMSTdKQmhMNEpmQWN1RlJDZXozc1FaRDg1UjV2RXVSa0lrYnV6M1hwNVQweS9MSVVtVTJ4Z3JuT29Xa1VnTjZ3TE15aWt2ckpobWp0TkZIN0k3TGczSVN2RE5mUUlwdVRtVk09IiwiZXhwIjoxNjE4MTk5NDU4LCJpYXQiOjE2MTgxOTIyNTh9.i0yczJwyR3wllRP6UFbHr5Oo7o-k6gUiruK1MJwSsh0

###
# 根据账号查询用户
GET http://localhost:8003/api/user/usernum?num=003
Accept: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJZQXRFZ0VpNnBQdy9YalV2NU1xTTlSNnhKM3g0VGpXeG5BMTNRS0ZiUDVGN1M5OWlOTkV0dnVwS1lUcCtGN2VkZXZmZVk0ZXRMSTdKQmhMNEpmQWN1RlJDZXozc1FaRDg1UjV2RXVSa0lrYnV6M1hwNVQweS9MSVVtVTJ4Z3JuT29Xa1VnTjZ3TE15aWt2ckpobWp0TkZIN0k3TGczSVN2RE5mUUlwdVRtVk09IiwiZXhwIjoxNjE4MTk5NDU4LCJpYXQiOjE2MTgxOTIyNTh9.i0yczJwyR3wllRP6UFbHr5Oo7o-k6gUiruK1MJwSsh0

###
#根据id查询用户
GET http://localhost:8003/api/user/userid/1
Accept: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJZQXRFZ0VpNnBQdy9YalV2NU1xTTlSNnhKM3g0VGpXeG5BMTNRS0ZiUDVGN1M5OWlOTkV0dnVwS1lUcCtGN2VkZXZmZVk0ZXRMSTdKQmhMNEpmQWN1RlJDZXozc1FaRDg1UjV2RXVSa0lrYnV6M1hwNVQweS9MSVVtVTJ4Z3JuT29Xa1VnTjZ3TE15aWt2ckpobWp0TkZIN0k3TGczSVN2RE5mUUlwdVRtVk09IiwiZXhwIjoxNjE4MTk5NDU4LCJpYXQiOjE2MTgxOTIyNTh9.i0yczJwyR3wllRP6UFbHr5Oo7o-k6gUiruK1MJwSsh0

###
#查询所有用户
GET http://localhost:8003/api/user/users
Accept: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJYZXhzRWhpMVRDVno5cUgxYjZaUDF6VTBteHV1RUhVTG9pamNCZFhqWEZRa29heFJXWDV0WHN6UkJvMkRlMjk0d2Z6Q0hzZzNxdlpDc0t1ME5NTFFrODl2WDg0aE9HMHNBT1pQak5hakMxU0g5SCszdk9Fd3BsR0VQRXo1SU43dStsR2oxSDBEVjFNSmNkWXhaMVlOUzNEVjdtOEJ0S0p6TDdvT084Y2k5NVk9IiwiZXhwIjoxNjE4MjExOTQyLCJpYXQiOjE2MTgyMDQ3NDJ9.K3QRoIiFycLHv7p_GTj_JhTCAfpMOpF-0ZG7q59XVKk

###
#更新用户，需要传入id
PATCH http://localhost:8003/api/user/user
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJZQXRFZ0VpNnBQdy9YalV2NU1xTTlSNnhKM3g0VGpXeG5BMTNRS0ZiUDVGN1M5OWlOTkV0dnVwS1lUcCtGN2VkZXZmZVk0ZXRMSTdKQmhMNEpmQWN1RlJDZXozc1FaRDg1UjV2RXVSa0lrYnV6M1hwNVQweS9MSVVtVTJ4Z3JuT29Xa1VnTjZ3TE15aWt2ckpobWp0TkZIN0k3TGczSVN2RE5mUUlwdVRtVk09IiwiZXhwIjoxNjE4MTk5NDU4LCJpYXQiOjE2MTgxOTIyNTh9.i0yczJwyR3wllRP6UFbHr5Oo7o-k6gUiruK1MJwSsh0

{
  "id": 3,
  "name": "张三",
  "num": "001",
  "password": "123456",
  "icon": "0213"
}

###
#删除用户
DELETE http://localhost:8003/api/user/user?id=2
Accept: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJZQXRFZ0VpNnBQdy9YalV2NU1xTTlSNnhKM3g0VGpXeG5BMTNRS0ZiUDVGN1M5OWlOTkV0dnVwS1lUcCtGN2VkZXZmZVk0ZXRMSTdKQmhMNEpmQWN1RlJDZXozc1FaRDg1UjV2RXVSa0lrYnV6M1hwNVQweS9MSVVtVTJ4Z3JuT29Xa1VnTjZ3TE15aWt2ckpobWp0TkZIN0k3TGczSVN2RE5mUUlwdVRtVk09IiwiZXhwIjoxNjE4MTk5NDU4LCJpYXQiOjE2MTgxOTIyNTh9.i0yczJwyR3wllRP6UFbHr5Oo7o-k6gUiruK1MJwSsh0

###
#添加用户
POST http://localhost:8003/api/user/user
Content-Type: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJZQXRFZ0VpNnBQdy9YalV2NU1xTTlSNnhKM3g0VGpXeG5BMTNRS0ZiUDVGN1M5OWlOTkV0dnVwS1lUcCtGN2VkZXZmZVk0ZXRMSTdKQmhMNEpmQWN1RlJDZXozc1FaRDg1UjV2RXVSa0lrYnV6M1hwNVQweS9MSVVtVTJ4Z3JuT29Xa1VnTjZ3TE15aWt2ckpobWp0TkZIN0k3TGczSVN2RE5mUUlwdVRtVk09IiwiZXhwIjoxNjE4MTk5NDU4LCJpYXQiOjE2MTgxOTIyNTh9.i0yczJwyR3wllRP6UFbHr5Oo7o-k6gUiruK1MJwSsh0

{
  "name": "王雷",
  "num": "002",
  "password": "123456",
  "icon": "D://xxx"
}

###
#token续期
GET http://localhost:8003/api/renew
Accept: application/json
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJYZXhzRWhpMVRDVno5cUgxYjZaUDF6VTBteHV1RUhVTG9pamNCZFhqWEZRa29heFJXWDV0WHN6UkJvMkRlMjk0d2Z6Q0hzZzNxdlpDc0t1ME5NTFFrODl2WDg0aE9HMHNBT1pQak5hakMxU0g5SCszdk9Fd3BsR0VQRXo1SU43dStsR2oxSDBEVjFNSmNkWXhaMVlOUzNEVjdtOEJ0S0p6TDdvT084Y2k5NVk9IiwiZXhwIjoxNjE4MjExMTE2LCJpYXQiOjE2MTgyMDM5MTZ9.I8PyqqnJLok2o0J0oEXiBFpKUgIKN7_2_5NYcW053Zg


###
#登陆
POST http://localhost:8003/api/login?verifyCode=R9QY
Content-Type: application/json

{
  "num": "002",
  "password": "123456"
}

###
#验证码
GET http://localhost:8003/api/verifyCode?timestamp=1618204674676
Accept: application/json